# @format
bot:
  ID: '1356380194306523300'
  TOKEN: '252352352'
  PREFIX: '-'
  EMBED_COLOR: '#ff0000'
  OWNERS: ['1306642651658981459']
  MONGO: ''
links:
  INVITE: 'https://discord.com/oauth2/authorize?client_id=1356380194306523300&permissions=8&integration_type=0&scope=bot'
  SUPPORT: 'https://dsc.gg/codexdev'
  VOTE: 'https://top.gg/bot/1356380194306523300/vote'
